app: gitscope-backend
service: gitscope-backend

custom:
  environment:
    ORIGIN:
      prod: https://gitscope.vercel.app
      dev: http://localhost:4000

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1 # ap-northeast-1
  environment:
    NODE_ENV: ${opt:stage}
    GITHUB_CLIENT_ID: ${ssm:/gitscope/${opt:stage}/githubClientId}
    GITHUB_CLIENT_SECRET: ${ssm:/gitscope/${opt:stage}/githubClientSecret}
    ORIGIN: ${self:custom.environment.ORIGIN.${opt:stage}}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  main:
    handler: src/handler/authHandler.main
    events:
      - http:
          path: /auth/github/callback
          method: get
          cors:
            origin: ${self:custom.environment.ORIGIN.${opt:stage}}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  repos:
    handler: src/handler/reposHandler.main
    events:
      - http:
          path: /repos
          method: get
          cors:
            origin: ${self:custom.environment.ORIGIN.${opt:stage}}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  mergedPullRequestsPerDay:
    handler: src/handler/mergedPullRequestsPerDay.main
    events:
      - http:
          path: /repos/{repositoryOwner}/{repositoryName}/prs
          method: get
          cors:
            origin: ${self:custom.environment.ORIGIN.${opt:stage}}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          request:
            parameters:
              querystrings:
                startDateString: false
                endDateString: false
              paths:
                repositoryOwner: true
                repositoryName: true
